# Generated by Django 5.1.2 on 2024-10-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='commentmodel',
            name='Comments_created_dd14cd_idx',
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['created'], name='blog_commen_created_0e3a0f_idx'),
        ),
        migrations.AlterModelTable(
            name='commentmodel',
            table=None,
        ),
    ]
